CREATE DATABASE IF NOT EXISTS koreauniv;

ALTER DATABASE koreauniv
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON koreauniv.* TO pc@localhost IDENTIFIED BY 'pc';

USE koreauniv;

CREATE TABLE IF NOT EXISTS employee (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  emp_id VARCHAR(24) NOT NULL,
  name VARCHAR(120),
  admin INT(1) UNSIGNED NOT NULL,
  INDEX(name)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS language (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30),
  test_name VARCHAR(30),
  INDEX(name)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS major (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120),
  INDEX(name)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS club (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  INDEX(name)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS country (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  INDEX(name)
) engine=InnoDB;

--CREATE TABLE IF NOT EXISTS types (
--  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--  name VARCHAR(80),
--  INDEX(name)
--) engine=InnoDB;
--
--CREATE TABLE IF NOT EXISTS owners (
--  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--  first_name VARCHAR(30),
--  last_name VARCHAR(30),
--  address VARCHAR(255),
--  city VARCHAR(80),
--  telephone VARCHAR(20),
--  INDEX(last_name)
--) engine=InnoDB;
--
--CREATE TABLE IF NOT EXISTS pets (
--  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--  name VARCHAR(30),
--  birth_date DATE,
--  type_id INT(4) UNSIGNED NOT NULL,
--  owner_id INT(4) UNSIGNED NOT NULL,
--  INDEX(name),
--  FOREIGN KEY (owner_id) REFERENCES owners(id),
--  FOREIGN KEY (type_id) REFERENCES types(id)
--) engine=InnoDB;
--
--CREATE TABLE IF NOT EXISTS visits (
--  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
--  pet_id INT(4) UNSIGNED NOT NULL,
--  visit_date DATE,
--  description VARCHAR(255),
--  FOREIGN KEY (pet_id) REFERENCES pets(id)
--) engine=InnoDB;
